### ISSUE TITLE
the manage button of the root is wrongly linked

### ISSUE THREAD

**Issue by individual-it** [owncloud/moodle-repository_ocis#50]
the 'manage' button of the root jumps to the last listed space

**Comment by individual-it** [comment]
should be fixed by #51

**Comment by PhMemmel** [comment]
As #51 has already been merged and I am running 69a149471e0ce86b8ee71b24ebd4cb3c63ab95c3 (which is latest commit on main) on my testing instance this bug still seems to be there.

The "manage" button now leads the user to the service base URL of the oauth2 service.

@individual-it Could you please doublecheck?

**Comment by individual-it** [comment]
@PhMemmel please try #71
